[package]
name = "diorama"
version = "0.1.0"
edition = "2024"
default-run = "diorama"

[dependencies]
raylib = "6.0.0"
nokhwa = { version = "0.10.7", default-features = false, features = ["input-native"] }
rand = "0.8"

[[bin]]
name = "tide_dash"
path = "src/minigame/tide_dash.rs"

[[bin]]
name = "star_squadron"
path = "src/minigame/star_squadron.rs"
